import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'

const pretendard = localFont({
  src: [
    {
      path: "./fonts/pretendard/PretendardVariable.woff2",
      weight: "100 900",
      style: "normal",
    },
  ],
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pretendard.variable}`}>
      <body className={pretendard.className}>
        {children}
      </body>
    </html>
  );
}
